LOCAL_PATH := $(call my-dir)



ifeq (${TARGET_ARCH_ABI},armeabi-v7a)
include $(CLEAR_VARS)
LOCAL_MODULE:= exe_thumb
LOCAL_SRC_FILES := testexe.cpp
LOCAL_C_INCLUDES :=
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
#LOCAL_ARM_MODE=arm
LOCAL_ARM_NEON := true
LOCAL_SHARED_LIBRARIES =
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_MODULE:= exe_arm
LOCAL_SRC_FILES := testexe.cpp
LOCAL_C_INCLUDES :=
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
LOCAL_ARM_MODE=arm
LOCAL_ARM_NEON := true
LOCAL_SHARED_LIBRARIES =
include $(BUILD_EXECUTABLE)
endif


ifeq (${TARGET_ARCH_ABI},arm64-v8a)
include $(CLEAR_VARS)
LOCAL_MODULE:= exe_arm64
LOCAL_SRC_FILES := testexe.cpp
LOCAL_C_INCLUDES :=
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
LOCAL_ARM_NEON := true
LOCAL_SHARED_LIBRARIES =
include $(BUILD_EXECUTABLE)
endif

